# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c6a390c86a5eaa018b527e7c408c825896c2eba6cbcb028cb0b6f82e823b3ce64e6127a7b3dbcd67272eb084e0e91d0a97a5ea5e0b7eb292ac30162f88cb459

test:
  secret_key_base: 26c5e86de6d721db13f57d5abcb548f7c4c4b91ce878082661ba46603a2b4701467b0f96c9b5155d77b65745e09ec196b3135d7bf417ee618d19ab4e7b0d875e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
